{{- if .Values.lightspeedCore.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lightspeedCore.apiKeySecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin-backend.lightspeedCore.labels" . | nindent 4 }}
type: Opaque
stringData:
  apitoken: {{ .Values.lightspeedCore.apiKey | quote }}
{{- end }}

