{{- if .Values.k8sMcp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin-prereqs.k8sMcp.labels" . | nindent 4 }}
{{- end }}

