{{- if .Values.nguiMcp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngui-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin-prereqs.nguiMcp.labels" . | nindent 4 }}
{{- end }}

